source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

workspace 'DemoApp'
target 'DemoApp' do
  pod 'avocarrot-ios-sdk/Full', '~> 4.10.0'
  pod 'SDWebImage'
  pod 'DZNSegmentedControl'
end

target 'DemoAppSwift' do
  pod 'avocarrot-ios-sdk/Full', '~> 4.10.0'
  pod 'SDWebImage'
  pod 'DZNSegmentedControl'

# Optional report system for QA
  pod 'Fabric'
  pod 'Crashlytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
